title: Samuel Hulse
description: "Theoretical Evolutionary Biologist"
email: shulse@umd.du
github_username: svhulse
google_scholar: https://scholar.google.com/citations?user=NLkuoc4AAAAJ&hl=en

theme:  minima
plugins:
  - jekyll-feed
